config/routes.rb
Rails.application.routes.draw do

  root "pstudents#home", as: :home

  post 'pstudents/create' => 'pstudents#create', as: :create_pstudent

  get 'applications/new' => 'applications#new', as: :new_application
  post 'applications/create' => 'applications#create', as: :create_application
  get 'applications/thankyou' => 'applications#thankyou', as: :thank_you

  get '/nosotros' => 'pstudents#nosotros', as: :nosotros
  get '/cursos' => 'pstudents#cursos', as: :cursos
  get '/newsletter' => 'pstudents#newsletter_form', as: :newsletter_form
  get '/terms' => 'pstudents#terms', as: :terms
  get '/privacy' => 'pstudents#privacy', as: :privacy
  get '/metodologia' => 'pstudents#methodology', as: :methodology
  get '/cursos/htmlycss' => 'pstudents#curso_htmlcss', as: :curso_htmlcss
  get '/cursos/mysql' => 'pstudents#curso_mysql', as: :curso_mysql
  get '/cursos/js' => 'pstudents#curso_js', as: :curso_js

  get '/applications' => 'applications#show', as: :applications

  post 'pstudents/quickform' => 'pstudents#create_qf', as: :create_pstudent_qf

  post 'pstudents/create_jslandingform' => 'pstudents#create_js', as: :create_pstudent_js

end

app/models/application.rb
class Application < ActiveRecord::Base

   validates :first_name, presence: true
   validates :last_name_materno, presence: true
   validates :last_name_paterno, presence: true
   validates :email, presence: true
   validates :phone, presence: true
   validates :DOB_day, presence: true
   validates :DOB_month, presence: true
   validates :DOB_year, presence: true
   validates :a1_como_te_enteraste, presence: true
   validates :a2_poque_HTMLyCSS, presence: true
   validates :a3_logictest1_Laura, presence: true
   validates :a4_logictest2_arboles, presence: true
   validates :requisitos, presence: true
   validates :universidad, presence: true
   validates :course, presence: true


end

app/models/applications.rb
class Applications < ActiveRecord::Base

   validates :first_name, presence: true
   validates :last_name_materno, presence: true
   validates :last_name_paterno, presence: true
   validates :email, presence: true
   validates :phone, presence: true
   validates :DOB_day, presence: true
   validates :DOB_month, presence: true
   validates :DOB_year, presence: true
   validates :a1_como_te_enteraste, presence: true
   validates :a2_poque_HTMLyCSS, presence: true
   validates :a3_logictest1_Laura, presence: true
   validates :a4_logictest2_arboles, presence: true

end

app/models/pstudent.rb
class Pstudent < ActiveRecord::Base

   validates :first_name, presence: true
   validates :last_name, presence: true
   validates :email, presence: true
   validates :fullname, presence: true
   validates :from_quickbutton, inclusion: { in: [ true, false ] }
   validates :from_js_landing, inclusion: { in: [ true, false ] }


   def full_name
     name = [self.first_name," ", self.last_name]
     name.join
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # @pstudent = Pstudent.new  

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def show

  end

  def new
    @application = Application.new
  end

  def create
    @application = Application.new
    @application.course = params[:application][:course]
    @application.first_name = params[:application][:first_name]
    @application.last_name_materno = params[:application][:last_name_materno]
    @application.last_name_paterno = params[:application][:last_name_paterno]
    @application.email = params[:application][:email]
    @application.phone = params[:application][:phone]
    @application.universidad = params[:application][:universidad]

    @application.DOB_day = params[:application][:DOB_day].to_i
    @application.DOB_month = params[:application][:DOB_month]
    @application.DOB_year = params[:application][:DOB_year].to_i

    @application.requisitos = params[:application][:requisitos]
    @application.a1_como_te_enteraste = params[:application][:a1_como_te_enteraste]
    @application.a2_poque_HTMLyCSS = params[:application][:a2_poque_HTMLyCSS]
    @application.a3_logictest1_Laura = params[:application][:a3_logictest1_Laura]
    @application.a4_logictest2_arboles = params[:application][:a4_logictest2_arboles]

    if @application.save
      redirect_to thank_you_path
    else
      flash[:notice] = "Hubo un error guardando tu solicitud.
      Acuérdate de llenar todos los campos siguiendo los ejemplos!"
      render :new
    end
  end

  def thankyou
        render layout: "thankyoulayout"

  end

end

app/controllers/pstudents_controller.rb
class PstudentsController < ApplicationController

  def home
    @pstudent = Pstudent.new
  end

  def newsletter_form
    @pstudent = Pstudent.new
  end

  def create
    @pstudent = Pstudent.new
    @pstudent.first_name = params[:pstudent][:first_name]
    @pstudent.last_name = params[:pstudent][:last_name]
    @pstudent.email = params[:pstudent][:email]
    @pstudent.fullname = "n/a"
    @pstudent.from_quickbutton = false
    @pstudent.from_js_landing = false

    if @pstudent.save
      redirect_to home_path,
      notice: "Ya estás inscrito(a) al newsletter. Pronto recibirás las últimas noticias
      de MUKTEK, además de descuentos para nuestra comunidad."
    else
      flash[:notice]= "Algo no funcinó registrando tus datos,
      por favor trata otra vez llenando todos los campos en la forma!"
      render :newsletter_form
    end
  end

  def newhome

  end

  def create_qf
    @pstudent = Pstudent.new
    @pstudent.first_name = params[:pstudent][:first_name]
    @pstudent.last_name = params[:pstudent][:last_name]
    @pstudent.email = params[:pstudent][:email]
    @pstudent.fullname = "n/a"
    @pstudent.from_quickbutton = true
    @pstudent.from_js_landing = false


    if @pstudent.save && request.xhr?
      head :ok
    else
      head :no_content
    end

  end

  def create_js
    @pstudent = Pstudent.new
    @pstudent.first_name = params[:pstudent][:first_name]
    @pstudent.last_name = "n/a"
    @pstudent.email = params[:pstudent][:email]
    @pstudent.fullname = "n/a"
    @pstudent.from_quickbutton = false
    @pstudent.from_js_landing = true

    if @pstudent.save
      redirect_to thank_you_path
    else
      flash[:notice] = "Hubo un error guardando tus datos.
      Acuérdate de llenar todos los campos siguiendo los ejemplos!"
      render :curso_js, layout: "jslandinglayout"
    end

  end

## NEW WEBSITE CODE

  def nosotros
    @pstudent = Pstudent.new
  end

  def cursos
    @pstudent = Pstudent.new
  end

  def terms
    @pstudent = Pstudent.new
  end

  def privacy
    @pstudent = Pstudent.new
  end
  def methodology
    @pstudent = Pstudent.new
  end

  def curso_htmlcss
    @pstudent = Pstudent.new
  end
  def curso_mysql
    @pstudent = Pstudent.new
  end

  def curso_js
    @pstudent = Pstudent.new
    render layout: "jslandinglayout"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/show.html.erb
<!-- <section class="BotMenu"><a href="/nosotros.html">
    <h2>NOSOTROS</h2></a><a href="/cursos.html">
    <h2>CURSOS</h2></a><a href="/inscripciones.html">
    <h2>INSCRIPCIONES</h2></a></section> -->


<section class="Hero Hero--small">
  <a href="/">
    <%= image_tag("muktek-logo.svg", :class => "Hero-logo", :alt => "Home logo") %>
    <!-- <img class="Hero-logo" src="/imgs/muktek-logo.svg" alt="Home logo"/> -->
  </a>
</section>
<section class="grid">
  <div class="col-1-of-3 copy__image" style="background-image: url(<%= asset_path('applications2_opt.jpg') %>);"></div>
  <div class="col copy copy--black">
    <h2 class="copy__title">Javascript Full-Stack</h2>
    <p>Full-Time <br/>Diario · Iniciamos 18 de Septiembre</br><br/>¿Quieres convertirte en desarrollador junior full-stack en 13 semanas?</br></p>
    <p class="p_button"><a class="button button--more-info margin_modification" href="/cursos/js">CHANGE YOUR LIFE NOW?</a></p>
  </div>
</section>
<section class="section--image" style="background-image:url(<%= asset_path('front_image_opt.jpg') %>);"></section>
<section class="section--quote">
  <h2 class="quote">Somos una academia de desarrollo de software enfocada en empoderar a los mexicanos con conocimientos en tecnología, <span class="colorletter">desde cero</span>.</h2>
</section>
<!-- <section class="grid">
  <div class="col copy__image" style="background-image: url(https://www.officelovin.com/wp-content/uploads/2015/09/the-den-office-coworking-2.jpg);"></div>
  <div class="col copy__image" style="background-image: url(https://www.officelovin.com/wp-content/uploads/2015/09/the-den-office-coworking-2.jpg);"></div>
  <div class="col copy__image" style="background-image: url(https://www.officelovin.com/wp-content/uploads/2015/09/the-den-office-coworking-2.jpg);"></div>
</section> -->
<section class="grid">
  <div class="col">
    <div class="copy copy--purple">
      <h2 class="copy__title">Introducción a HTML y CSS </br> <small><small>Excelente para diseñadores, emprendedoras, marketeros, y estudiantes</small></small></h2>
      <p>Part-Time <br/>Sabados · Iniciamos 15 de Julio</p><a class="link" href="/cursos/htmlycss">Más info</a>
      <p class="p_button"><a class="button button--more-info margin_modification" href="/applications/new">Postula</a></p>
    </div>
  </div>
  <div class="col-1-of-3 copy__image" style="background-image: url(<%= asset_path('applications1.jpg') %>);"></div>
</section>
<section class="grid">
  <div class="col-1-of-3 copy__image" style="background-image: url(<%= asset_path('nosotros3_opt.jpg') %>);"></div>
  <div class="col copy copy--light-green">
    <h2 class="copy__title">Introducción a MySQL </br> <small><small>Excelente para analistas de negocios, finanzas, y contadores</small></small></h2>
    <p>Part-Time <br/>Sabados · Iniciamos 12 de agosto</p><a class="link" href="/cursos/mysql">Más info</a>
    <p class="p_button"><a class="button button--more-info margin_modification" href="/applications/new">Postula</a></p>
  </div>
</section>
<!-- <section class="grid">
  <div class="col-1-of-3 copy__image" style="background-image: url(<%= asset_path('applications2_opt.jpg') %>);"></div>
  <div class="col copy copy--black">
    <h2 class="copy__title">Javascript Full-Stack</h2>
    <p>Full-Time <br/>Diario · Iniciamos 18 de Septiembre</br><br/>¿Quieres convertirte en desarrollador junior full-stack en 3 meses?</br></p>
    <p class="p_button"><a class="button button--more-info margin_modification" href="/newsletter">PIDE INFORMES</a></p>
  </div>
</section> -->

app/views/applications/thankyou.html.erb
<section class="Hero Hero--small">
  <a href="/">
    <%= image_tag("muktek-logo.svg", :class => "Hero-logo", :alt => "Home logo") %>
    <!-- <img class="Hero-logo" src="/imgs/muktek-logo.svg" alt="Home logo"/> -->
  </a>
</section>

<section class="section--quote copy--black">
  <h2 class="quote center">GRACIAS</h2>
</section>

<div class="modal__content copy--black">
  <div class="container_newURL">
    <div class="container">
      <p class="largepar center">
          Estaremos en contacto contigo lo antes posible con una respuesta
      <br><br><br><br><br><br>
      </p>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Code from Google to verify the domain muktek.com  -->
  <meta name="google-site-verification" content="f306wjC5cDbm515q_mrAuZlHPlvLMT1pK3zcy60xgv4" />

<!-- setting website tab title -->
  <title>Aprende a codear y hackear desde cero. Dedícate al desarrollo de software. MUKTEK</title>



  <!-- SOCIAL -->
  <meta property="og:image" content="https://pbs.twimg.com/profile_images/829700759352598528/E54Ok8m0.jpg">
  <meta name="og:description" content="Talento y tecnologia. desde el origen.
    Aprende los lenguajes del futuro.">
  <meta name="og:title" content="MUKTEK">
  <meta name="og:image:width" content="250">


  <meta name="og:url" content="https://www.muktek.com">
<!-- END SOCIAL -->

  <!-- adding MUKTEK icon to title -->
  <link rel="icon" type="image/png" href="<%= asset_path("MUKTEK2.png") %>" />


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="description" content="Talento y tecnologia. desde el origen.
    Aprende los lenguajes del futuro.">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">


<!-- Google analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-97464411-1', 'auto');
    ga('send', 'pageview');

  </script>

<!-- end google analytics -->

    <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '313948169018009'); // Insert your pixel ID here.
        fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=313948169018009&ev=PageView&noscript=1"
        /></noscript>
  <!-- DO NOT MODIFY -->
  <!-- End Facebook Pixel Code -->



  <!-- Site version July 1, 2017 -->
  <script src="https://use.fontawesome.com/d441c6b6c6.js"></script>
  <!-- end new version -->

</head>
<body>

  <header>
    <nav>
      <div id='nav'>
        <ul class='nav__list'>
          <li class="hamburger">
            <a href="#" id='icon' class="icon">
              <span class='icon__line'></span>
              <svg x="0px" y="0px" width="54px" height="54px" viewBox="0 0 54 54">
                <circle fill="transparent" stroke="#656e79" stroke-width="1" cx="27" cy="27" r="25" stroke-dasharray="157 157" stroke-dashoffset="157"></circle>
              </svg>
            </a>
          </li>
          <div class="nav__list__text" id='navtext'>
            <li><a href="/nosotros">Nosotros</a></li>
            <li><a href="/cursos">Cursos</a></li>
          </div>

        </ul>
        <div class='menu'>
          <div class='half'>
            <ul class='menu__list'>
              <li class='menuitem menu__top-item'><a href="/applications/new" class='selected'>Inscripciones</a></li>
              <li><a href="/cursos">Cursos</a></li>
              <li class="menu_smallitem"><a href="/cursos/js">Javascript Full Stack <small></small></a></li>
              <li class="menu_smallitem"><a href="/cursos/htmlycss">Introducción a HTML y CSS</a></li>
              <li class="menu_smallitem"><a href="/cursos/mysql">Introducción a MySQL <small></small></a></li>
              <li class='menuitem'><a href="/metodologia">Metodología</a></li>
              <!-- <li><a href="#">Formas de Pago</a></li> -->
              <li class='menuitem'><a href="/nosotros">Nosotros</a></li>
              <li class='menuitem'><a href="/newsletter">Newsletter</a></li>
              <li class='menuitem'><a href="https://medium.com/kan-by-muktek">Blog</a></li>
            </ul>
          </div>
          <div class='half'>
            <ul class='contact__list'>
              <li><a class='selected selected__contactemail' href="mailto:info@muktek.com">info@muktek.com</a></li>
              <li><span>55 7672 1135</span></li>
              <li><span>The Pool<br/> Toledo #39<br/>Juarez, CDMX</span></li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>


<%= yield %>


<section class="Footer">
  <div class="Footer-logo">
    <!-- <a href="/"> -->
      <%= image_tag("muktek-logo.svg", :alt => "MUKTEK logo") %>
    <!-- </a> -->
    <!-- <img src="/imgs/muktek-logo.svg" alt="Muktek Logo"/> -->
    <div class="Footer-logo-slogan">
      <h3>Talento y tecnologia<br/> desde el origen</h3><a class="link" href="/newsletter.html">SUBSCRIBETE A NUESTRO NEWSLETTER</a>
    </div>
  </div>
  <div class="Footer-social"><a href="https://www.facebook.com/fuerzamuktek" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="https://twitter.com/fuerzamuktek" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a><a href="https://www.instagram.com/fuerzamuktek" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a><a href="https://www.youtube.com/channel/UCbcj9G6EaXtYLqTDpVee09Q" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a></div>
  <div class="Footer-info">
    <ul>
      <li><a href="/terms">TERMINOS Y CONDICIONES</a></li>
      <li><a href="/privacy">AVISO DE PRIVACIDAD</a></li>
      <li>Contáctanos en: <a href="mailto:info@muktek.com">info@muktek.com</a></li>
    </ul>
  </div>
</section>


<!-- Version July 1, 2017 -->
<a href='#' id='news-trigger' class='news__trigger'><i class='fa fa-envelope-o'></i><span></span></a>
  <nav>
    <ul id='newsletter' class='newsletter'>
      <form>
        <h2 class='form-title'>Recibe informes y aprende a codear:</h2>
        <input class="form-control" placeholder="Nombre" type="text" name="pstudent[first_name]" id="pstudent_first_name">
        <!--<input class="form-control" placeholder="Apellido" type="text" name="pstudent[last_name]" id="pstudent_last_name">-->
        <input class="form-control" placeholder="Email" type="text" name="pstudent[email]" id="pstudent_email">

        <button type="submit" name="button" class='btn-submit'>Registrarme</button>
        <!--<button type='submit' data-remote='true' class="button button--line button--effect-1">
          <span class="morph-shape" data-morph-active="M286,113c0,0-68.8,9-136,9c-78.2,0-137-9-137-9S3,97.198,3,62.5C3,33.999,13,12,13,12S72,2,150,2c85,0,136,10,136,10s11,17.598,11,52C297,96.398,286,113,286,113z">
            <svg width="100%" height="100%" viewBox="0 0 300 125" preserveAspectRatio="none">
              <path d="M286.5,113c0,0-104,0-136.5,0c-35.75,0-136.5,0-136.5,0s0-39.417,0-52.5c0-12.167,0-48.5,0-48.5s101.833,0,136.5,0c33.583,0,136.5,0,136.5,0s0,35.917,0,48.5C286.5,73.167,286.5,113,286.5,113z"/>
            </svg>
          </span>
          <span class="button__text">Inscribirme</span>
        </button>-->
      </form>
    </ul>
  </nav>
<!-- end new version  -->


<!-- <script src="https://use.fontawesome.com/8442e6330f.js"></script> -->


  <script>
    var icon = document.getElementById('icon');
    var nav = document.getElementById('nav');
    var navtext = document.getElementById('navtext');
    var news = document.getElementById('news-trigger');
    var newsNav = document.getElementById('newsletter');

    icon.addEventListener('click', function(e) {
      e.preventDefault();
      nav.classList.toggle('is-open');
      navtext.classList.toggle('hide_text');
      navtext.classList.toggle ('nav__list__text');
    });

    news.addEventListener('click', function(e) {
      e.preventDefault();
      this.classList.toggle('is-open');
      newsNav.classList.toggle('is-open');
    });

    $('.newsletter button').on('click', function() {
      $.post('/pstudents/quickform', {
        pstudent: {
          first_name: $('#pstudent_first_name').val(),
          // last_name: $('#pstudent_last_name').val(),
          // email: 'rovalcor@gmail.com',
          last_name: "NULL",
          email: $('#pstudent_email').val(),
        }
      }, () => {alert('Gracias, ¡estaremos en contacto muy pronto!')})
    })
  </script>

  <!-- <div style="display:none"> -->

  <!-- Google remarketing -->
          <!-- Google Code para etiquetas de remarketing -->
          <!--
          Es posible que las etiquetas de remarketing todavía no estén asociadas a la información de identificación personal o que estén en páginas relacionadas con las categorías delicadas. Para obtener más información e instrucciones sobre cómo configurar la etiqueta, consulte http://google.com/ads/remarketingsetup.
          --------------------------------------------------->
          <script type="text/javascript">
          /* <![CDATA[ */
          var google_conversion_id = 845489174;
          var google_custom_params = window.google_tag_params;
          var google_remarketing_only = true;
          /* ]]> */
          </script>
          <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
          </script>
          <noscript>
            <div style="display:inline;">
              <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/845489174/?guid=ON&amp;script=0"/>
            </div>
          </noscript>

  <!-- end Google Remarketing -->


  <!-- </div> -->

  <!-- Start of HubSpot Embed Code -->
  <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/3476655.js"></script>
<!-- End of HubSpot Embed Code -->


</body>
</html>

app/views/pstudents/newhome.html.erb
  <!-- <div class="row"> -->
    <div class="col-sm-10 col-sm-offset-1 screenshot1">
      <%= image_tag("NewSite_Alumno_ScreenShot.png")%>
    </div>
    <div class="col-sm-1 logo2">
      <a href="/">
      <%= image_tag("MUKTEK_2.png")%>
      <!-- <h5>Regresar</h5> -->
      <p><a class="btn btn-primary btn-lg btnregresar" href="/" role="button">Regresar</a></p>

      </a>
    </div>

  <!-- </div> -->

app/views/pstudents/newsletter_form.html.erb
<div class="row alert">
         <div class="col-sm-9 col-sm-offset-2">
           <% if notice %>
             <div class="alert alert-info alert-dismissible" role="alert">
               <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
               <p> <%= notice %>  </p>
             </div>
           <% end %>
         </div>
</div>

<!-- <section class="BotMenu"><a href="/nosotros.html">
    <h2>NOSOTROS</h2></a><a href="/cursos.html">
    <h2>CURSOS</h2></a><a href="/inscripciones.html">
    <h2>INSCRIPCIONES</h2></a></section> -->
<section class="Hero Hero--small">
  <a href="/">
    <%= image_tag("muktek-logo.svg", :class => "Hero-logo", :alt => "Home logo") %>
    <!-- <img class="Hero-logo" src="/imgs/muktek-logo.svg" alt="Home logo"/> -->
  </a>
</section>
<section class="section--quote">
  <h2 class="quote">Para estar enterado(a) de lo último que sucede en MUKTEK, además de tener acceso a descuentos especiales para nuestros cursos, inscríbete a nuestro newsletter</h2>
</section>
<section class="section--inscription">
  <h2 class="form__subtitle">Newsletter Sign-Up</h2>
  <%= form_for @pstudent, url: create_pstudent_path do |f| %>
       <div class="formfield first_name">
         <%= f.text_field :first_name, class: 'form-control', placeholder: "Nombre"  %>
       </div>
       <div class="formfield last_name">
         <%= f.text_field :last_name, class: 'form-control', placeholder: "Apellido"  %>
       </div>
       <div class="formfield last_name">
         <%= f.text_field :email, class: 'form-control', placeholder: "email"  %>
       </div>
       <div class="submit_button">
         <%= f.submit "Inscribirme!", class: "button button--cta"%>
       </div>
   <% end %>
  <!-- <form id="new_pstudent" action="/pstudents/create" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="ROrtwJLTYLGJKLfLBLMyRWZOX65wyoyKv6btAv2X9o3bLfgApYd5AV/T6Yw41LjnfamGJpFE5rwat9njYK8ZKg==">
    <div>
      <input required class="form-control" placeholder="Nombre" type="text" name="pstudent[first_name]" id="pstudent_first_name">
    </div>
    <div>
      <input class="form-control" placeholder="Apellido" type="text" name="pstudent[last_name]" id="pstudent_last_name">
    </div>
    <div>
      <input required class="form-control" placeholder="email" type="text" name="pstudent[email]" id="pstudent_email">
    </div>
    <div>
      <input class="button button--cta" type="submit" name="commit" value="Inscribirme!">
    </div>
  </form> -->


</section>